// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createToken = `-- name: CreateToken :one
INSERT INTO loginpl (email)
VALUES (?)
RETURNING id
`

func (q *Queries) CreateToken(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRowContext(ctx, createToken, email)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteTokenByEmail = `-- name: DeleteTokenByEmail :exec
DELETE FROM loginpl
WHERE email = ?
`

func (q *Queries) DeleteTokenByEmail(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, deleteTokenByEmail, email)
	return err
}

const getTokenByEmail = `-- name: GetTokenByEmail :one


SELECT id, created_at
FROM loginpl
WHERE email = ?
LIMIT 1
`

type GetTokenByEmailRow struct {
	ID        string       `json:"id"`
	CreatedAt sql.NullTime `json:"created_at"`
}

// Session management
func (q *Queries) GetTokenByEmail(ctx context.Context, email string) (GetTokenByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getTokenByEmail, email)
	var i GetTokenByEmailRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
