// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type Loginpl struct {
	ID             string       `json:"id"`
	Email          string       `json:"email"`
	CounterRequest int64        `json:"counter_request"`
	CreatedAt      sql.NullTime `json:"created_at"`
}

type Organization struct {
	ID                     string         `json:"id"`
	Name                   string         `json:"name"`
	Description            sql.NullString `json:"description"`
	HolderAccount          int64          `json:"holder_account"`
	HolderAccountEvaluator int64          `json:"holder_account_evaluator"`
	ProgramType            string         `json:"program_type"`
	Logo                   sql.NullString `json:"logo"`
	CreatedAt              time.Time      `json:"created_at"`
	UpdatedAt              time.Time      `json:"updated_at"`
}

type Profile struct {
	ID             string         `json:"id"`
	Username       sql.NullString `json:"username"`
	Phone          sql.NullString `json:"phone"`
	Email          string         `json:"email"`
	Role           string         `json:"role"`
	OrganizationID sql.NullString `json:"organization_id"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

type RevokedToken struct {
	ID        int64          `json:"id"`
	Jti       sql.NullString `json:"jti"`
	RevokedAt sql.NullTime   `json:"revoked_at"`
	ExpiresAt sql.NullTime   `json:"expires_at"`
}

type Session struct {
	ID           int64          `json:"id"`
	UserID       sql.NullString `json:"user_id"`
	RefreshToken sql.NullString `json:"refresh_token"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	ExpiresAt    sql.NullTime   `json:"expires_at"`
}
