// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profiles.sql

package db

import (
	"context"
	"database/sql"
)

const createProfile = `-- name: CreateProfile :one

INSERT INTO profiles (id, username, phone, email, role, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, username, phone, email, role, created_at, updated_at
`

type CreateProfileParams struct {
	ID       string         `json:"id"`
	Username sql.NullString `json:"username"`
	Phone    sql.NullString `json:"phone"`
	Email    string         `json:"email"`
	Role     string         `json:"role"`
}

type CreateProfileRow struct {
	ID        string         `json:"id"`
	Username  sql.NullString `json:"username"`
	Phone     sql.NullString `json:"phone"`
	Email     string         `json:"email"`
	Role      string         `json:"role"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

// Profile management
func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (CreateProfileRow, error) {
	row := q.db.QueryRowContext(ctx, createProfile,
		arg.ID,
		arg.Username,
		arg.Phone,
		arg.Email,
		arg.Role,
	)
	var i CreateProfileRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Phone,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProfileByID = `-- name: DeleteProfileByID :exec
DELETE FROM profiles
WHERE id = ?
`

func (q *Queries) DeleteProfileByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProfileByID, id)
	return err
}

const getProfileByEmail = `-- name: GetProfileByEmail :one
SELECT id, username, phone, email, role, created_at, updated_at
FROM profiles
WHERE email = ?
LIMIT 1
`

type GetProfileByEmailRow struct {
	ID        string         `json:"id"`
	Username  sql.NullString `json:"username"`
	Phone     sql.NullString `json:"phone"`
	Email     string         `json:"email"`
	Role      string         `json:"role"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

func (q *Queries) GetProfileByEmail(ctx context.Context, email string) (GetProfileByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getProfileByEmail, email)
	var i GetProfileByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Phone,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileByID = `-- name: GetProfileByID :one
SELECT id, username, phone, email, role, created_at, updated_at
FROM profiles
WHERE id = ?
`

type GetProfileByIDRow struct {
	ID        string         `json:"id"`
	Username  sql.NullString `json:"username"`
	Phone     sql.NullString `json:"phone"`
	Email     string         `json:"email"`
	Role      string         `json:"role"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

func (q *Queries) GetProfileByID(ctx context.Context, id string) (GetProfileByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProfileByID, id)
	var i GetProfileByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Phone,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileByPhone = `-- name: GetProfileByPhone :one
SELECT id, username, phone, email, role, created_at, updated_at
FROM profiles
WHERE phone = ?
LIMIT 1
`

type GetProfileByPhoneRow struct {
	ID        string         `json:"id"`
	Username  sql.NullString `json:"username"`
	Phone     sql.NullString `json:"phone"`
	Email     string         `json:"email"`
	Role      string         `json:"role"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

func (q *Queries) GetProfileByPhone(ctx context.Context, phone sql.NullString) (GetProfileByPhoneRow, error) {
	row := q.db.QueryRowContext(ctx, getProfileByPhone, phone)
	var i GetProfileByPhoneRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Phone,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileByUsername = `-- name: GetProfileByUsername :one
SELECT id, username, phone, email, role, created_at, updated_at
FROM profiles
WHERE username = ?
LIMIT 1
`

type GetProfileByUsernameRow struct {
	ID        string         `json:"id"`
	Username  sql.NullString `json:"username"`
	Phone     sql.NullString `json:"phone"`
	Email     string         `json:"email"`
	Role      string         `json:"role"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

func (q *Queries) GetProfileByUsername(ctx context.Context, username sql.NullString) (GetProfileByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getProfileByUsername, username)
	var i GetProfileByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Phone,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProfilesByRole = `-- name: ListProfilesByRole :many
SELECT id, username, phone, email, role, created_at, updated_at
FROM profiles
WHERE role = ?
ORDER BY created_at DESC
`

type ListProfilesByRoleRow struct {
	ID        string         `json:"id"`
	Username  sql.NullString `json:"username"`
	Phone     sql.NullString `json:"phone"`
	Email     string         `json:"email"`
	Role      string         `json:"role"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

func (q *Queries) ListProfilesByRole(ctx context.Context, role string) ([]ListProfilesByRoleRow, error) {
	rows, err := q.db.QueryContext(ctx, listProfilesByRole, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProfilesByRoleRow
	for rows.Next() {
		var i ListProfilesByRoleRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Phone,
			&i.Email,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE profiles
SET username = COALESCE(?, username),
    phone = COALESCE(?, phone),
    email = COALESCE(?, email),
    role = COALESCE(?, role),
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, username, phone, email, role, created_at, updated_at
`

type UpdateProfileParams struct {
	Username sql.NullString `json:"username"`
	Phone    sql.NullString `json:"phone"`
	Email    string         `json:"email"`
	Role     string         `json:"role"`
	ID       string         `json:"id"`
}

type UpdateProfileRow struct {
	ID        string         `json:"id"`
	Username  sql.NullString `json:"username"`
	Phone     sql.NullString `json:"phone"`
	Email     string         `json:"email"`
	Role      string         `json:"role"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (UpdateProfileRow, error) {
	row := q.db.QueryRowContext(ctx, updateProfile,
		arg.Username,
		arg.Phone,
		arg.Email,
		arg.Role,
		arg.ID,
	)
	var i UpdateProfileRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Phone,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProfileRole = `-- name: UpdateProfileRole :one
UPDATE profiles
SET role = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, username, phone, email, role, created_at, updated_at
`

type UpdateProfileRoleParams struct {
	Role string `json:"role"`
	ID   string `json:"id"`
}

type UpdateProfileRoleRow struct {
	ID        string         `json:"id"`
	Username  sql.NullString `json:"username"`
	Phone     sql.NullString `json:"phone"`
	Email     string         `json:"email"`
	Role      string         `json:"role"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

func (q *Queries) UpdateProfileRole(ctx context.Context, arg UpdateProfileRoleParams) (UpdateProfileRoleRow, error) {
	row := q.db.QueryRowContext(ctx, updateProfileRole, arg.Role, arg.ID)
	var i UpdateProfileRoleRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Phone,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
