// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profiles.sql

package sqlc

import (
	"context"
)

const checkUserEmailExists = `-- name: CheckUserEmailExists :one

SELECT COUNT(1) AS count
FROM profiles
WHERE email = ?
`

// Profile management
func (q *Queries) CheckUserEmailExists(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkUserEmailExists, email)
	var count int64
	err := row.Scan(&count)
	return count, err
}
