// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	// Profile management
	CheckUserEmailExists(ctx context.Context, email string) (int64, error)
	CreateToken(ctx context.Context, email string) (string, error)
	DeleteTokenByEmail(ctx context.Context, email string) error
	// Session management
	GetTokenByEmail(ctx context.Context, email string) (GetTokenByEmailRow, error)
	UpdateTokenCount(ctx context.Context, email string) (string, error)
}

var _ Querier = (*Queries)(nil)
